# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/plugins/log_plugin.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'app/plugins/log_plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pp/plugins/log_plugin.proto\x12\tlogplugin\"\x8c\x01\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttf_req_id\x18\x04 \x01(\t\x12\x0e\n\x06tf_rpc\x18\x05 \x01(\t\x12\x18\n\x10tf_resource_type\x18\x06 \x01(\t\x12\x10\n\x08raw_json\x18\x07 \x01(\t\"\x94\x01\n\nLogRequest\x12!\n\x04logs\x18\x01 \x03(\x0b\x32\x13.logplugin.LogEntry\x12\x33\n\x07options\x18\x02 \x03(\x0b\x32\".logplugin.LogRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x0bLogResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.logplugin.ProcessedResult\x12\x0f\n\x07summary\x18\x02 \x01(\t\"M\n\x0fProcessedResult\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0f\n\x07log_ids\x18\x04 \x03(\t2I\n\tLogPlugin\x12<\n\x0bProcessLogs\x12\x15.logplugin.LogRequest\x1a\x16.logplugin.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.plugins.log_plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_LOGREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=44
  _globals['_LOGENTRY']._serialized_end=184
  _globals['_LOGREQUEST']._serialized_start=187
  _globals['_LOGREQUEST']._serialized_end=335
  _globals['_LOGREQUEST_OPTIONSENTRY']._serialized_start=289
  _globals['_LOGREQUEST_OPTIONSENTRY']._serialized_end=335
  _globals['_LOGRESPONSE']._serialized_start=337
  _globals['_LOGRESPONSE']._serialized_end=412
  _globals['_PROCESSEDRESULT']._serialized_start=414
  _globals['_PROCESSEDRESULT']._serialized_end=491
  _globals['_LOGPLUGIN']._serialized_start=493
  _globals['_LOGPLUGIN']._serialized_end=566
# @@protoc_insertion_point(module_scope)
